apiVersion: apps/v1
kind: Deployment
metadata:
  name: ze-burguer-app
spec:
  selector:
    matchLabels:
      app:  ze-burguer
  template:
    metadata:
      labels:
        app: ze-burguer
    spec:
      containers:
        - name: ze-burguer
          image: marcosilva/ze_burguer:latest
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: ze-burguer
          - secretRef:
              name: ze-burguer
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: ze-burguer
spec:
  type: LoadBalancer
  selector:
    app: ze-burguer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ze-burguer
data:
  DATABASE_HOST: "rds-endpoint"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "ze_burguer"
  DATABASE_SCHEMA: "ze_burguer"
  DATABASE_USERNAME: "postgres"
  MIGRATIONS_DIR: "infra/database/migrations"
---
apiVersion: v1
kind: Secret
metadata:
  name: ze-burguer
type: Opaque
data:
  DATABASE_PASSWORD: bXlzZWNyZXQxMjMK
