name: Deploy Cluster Addons

on:
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: eks-ze-burguer
  AWS_REGION: us-east-1

jobs:
  deploy-addons:
    name: Deploy Addons
    runs-on: ubuntu-latest

    steps: 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy Metrics Server to EKS
      run: |
        kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
